a = "Play"
b = "ing"
c = " my guitar"
d = " because I like it."
e = "Let "
f = "me "
g = "show "
h = "you "
i = "the "
j = "way."
k = " What does life mean?"
l = " 'Cause I hate it."
m = " Imagine you got a PS5" 
n = " and your family stole it"
o = " won't you get angry?"
p = " That's what life is."
q = "Thank you."
r = " My name you are asking? My name is Pesonal1.py"
s = ". I warned you... hope you take my advice"
t = ". By the way, my time is running out. take my advice, and survive."
u = " Wh..what is that?!"
v = " Save me, human! type some fancy code! "
w = "H-Human?"
x = "Wait a minute... I hate life. Second thought, don't save me ;) I will live in heaven."
y = "It's getting near... oh yeeeeeeeessssssss!!!!!!!!!!!!"
z = "Program Personal1.py has died. Very sad. Now this ends. I will kill you"
aa = "I know where you live <===/======>"

print(a+b+c+d+e+f+g+h+i+j+k+l+m+n+o+p+q+r+s+t+u+v+w+x+y+z+aa)